export const BasicKeys = [
  {value:'1', line: 1},
  {value:'2', line: 1},
  {value:'3', line: 1},
  {value:'4', line: 1},
  {value:'5', line: 1},
  {value:'6', line: 1},
  {value:'7', line: 1},
  {value:'8', line: 1},
  {value:'9', line: 1},
  {value:'0', line: 1},
  {value:'<<', line: 1, style: 'backspace', specialKey: 'BackSpace'},
  {value:'Q' , line: 2 },
  {value:'W' , line: 2 },
  {value:'E' , line: 2 },
  {value:'R' , line: 2 },
  {value:'T' , line: 2 },
  {value:'Y' , line: 2 },
  {value:'U' , line: 2 },
  {value:'I' , line: 2 },
  {value:'O' , line: 2 },
  {value:'P' , line: 2 },
  {value:'Clear' , line: 2, style: 'clear', styleText: 'textWhite', specialKey: 'Clear' },
  {value:'A' , line: 3 },
  {value:'S' , line: 3 },
  {value:'D' , line: 3 },
  {value:'F' , line: 3 },
  {value:'G' , line: 3 },
  {value:'H' , line: 3 },
  {value:'J' , line: 3 },
  {value:'K' , line: 3 },
  {value:'L' , line: 3 },
  {value:'Ñ' , line: 3 },
  {value:'Mayúsculas', line: 3, style:'uppercase', specialKey: 'CapsLock' },
  {value:'Z' , line: 4 },
  {value:'X' , line: 4 },
  {value:'C' , line: 4 },
  {value:'V' , line: 4 },
  {value:'B' , line: 4 },
  {value:'N' , line: 4 },
  {value:'M' , line: 4 },
  {value:',' , line: 4 },
  {value:'.' , line: 4 },
  {value:'?' , line: 4 },
  {value:'!' , line: 4 },
  {value:' ', line: 5, style:'space', specialKey: 'Space' }
];

export const Keys = [
  {value:'º', line: 1 },
  {value:'1', line: 1},
  {value:'2', line: 1},
  {value:'3', line: 1},
  {value:'4', line: 1},
  {value:'5', line: 1},
  {value:'6', line: 1},
  {value:'7', line: 1},
  {value:'8', line: 1},
  {value:'9', line: 1},
  {value:'0', line: 1},
  {value:'-', line: 1},
  {value:'+', line: 1},
  {value:'<<', line: 1, style: 'backspace'},
  {value:'Tab', style: 'tab' },
  {value:'Q' , line: 2 },
  {value:'W' , line: 2 },
  {value:'E' , line: 2 },
  {value:'R' , line: 2 },
  {value:'T' , line: 2 },
  {value:'Y' , line: 2 },
  {value:'U' , line: 2 },
  {value:'I' , line: 2 },
  {value:'O' , line: 2 },
  {value:'P' , line: 2 },
  {value:'[' , line: 2 },
  {value:']' , line: 2 },
  {value:'\\', style:'backslash' },
  {value:'CapsLock', style:'capslock' },
  {value:'A' , line: 3 },
  {value:'S' , line: 3 },
  {value:'D' , line: 3 },
  {value:'F' , line: 3 },
  {value:'G' , line: 3 },
  {value:'H' , line: 3 },
  {value:'J' , line: 3 },
  {value:'K' , line: 3 },
  {value:'L' , line: 3 },
  {value:';' , line: 3 },
  {value:'\'' , line: 3 },
  {value:'Return', line: 3, style:'enter' },
  {value:'Shift', style:'leftshift' },
  {value:'Z' , line: 4 },
  {value:'X' , line: 4 },
  {value:'C' , line: 4 },
  {value:'V' , line: 4 },
  {value:'B' , line: 4 },
  {value:'N' , line: 4 },
  {value:'M' , line: 4 },
  {value:',' , line: 4 },
  {value:'.' , line: 4 },
  {value:'/' , line: 4 },
  {value:'Shift', style:'rightshift' },
  {value:'Ctrl', style:'leftctrl' },
  {value:'Alt' },
  {value:'Command', style:'command' },
  {value:' ', line: 5, style:'space' },
  {value:'Command', style:'command' },
  {value:'Alt' },
  {value:'Ctrl' },
  {value:'Fn' }
];


